site_name: MOT Benchmarking Docs
repo_name: benchmark_eval
repo_url: https://github.com/mbari-org/benchmark_eval
site_description: Documentation for MBARI's MOT benchmarking workflow

nav:
- "Home": index.md
- "Installation": installation.md
- "Usage": usage.md
- "Tips": tips.md

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

theme:
  name: material
  logo: https://docs.mbari.org/imgs/mbari-logo.png
  favicon: https://docs.mbari.org/imgs/mbari-logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: System theme
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: light
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Light mode
  icon:
    repo: material/github
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    # - toc.integrate
    - content.code.copy
