site_name: Benchmarking Docs
nav:
- Home: elaine_documentation.md
- Installation: installation.md
- Usage: usage.md
- Tips: tips.md

markdown_extensions:
  - meta
extra_css:
    - https://docs.mbari.org/css/mbari.css
theme:
  name: material
  logo: https://docs.mbari.org/imgs/mbari-logo.png
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode